#pragma config(Sensor, S1,     lightRight,     sensorLightActive)
#pragma config(Sensor, S2,     lightLeft,      sensorLightActive)
#pragma config(Sensor, S3,     EV3SMUX,        sensorI2CCustom)
#pragma config(Sensor, S4,     portSplitter,   sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RescueLine_TaskLibrary.h"

task main()
{
	MotorSetup();
	startTask(ReadSensors);
	while(true)
	{
		taskNo = 1;

		//Check if line is lost
		numberOfsensorsOnwhite = 0;
		for(int i = 0; i < 8; i++)
		{
			if(LightSensorArray[i].OnWhite)
			{
				numberOfsensorsOnwhite += 1;
			}
		}

		if(numberOfsensorsOnwhite == 8) //Line Regain
		{
			taskNo = 2;
		}
		else if((angle >= MIN_ANGLE_OF_ELEVATION && angle <= MAX_ANGLE_OF_ELEVATION) || (angle >= MAX_ANGLE_OF_DEPRESSION && angle <= MIN_ANGLE_OF_DEPRESSION)) //Ramp Line Follow
		{
			taskNo = 3;
		}
		else if(SensorValue(lightLeft) <= MAX_BLACK_LEFT && SensorValue(lightRight) <= MAX_BLACK_RIGHT) //Right Angle Turns
		{
			taskNo = 4;
		}
		else if(colourLeft.colour == GREEN || colourRight.colour == GREEN) //Intersection Turn
		{
			taskNo = 5;
		}
		else if(nI2CStatus[portSplitter] == ERR_COMM_BUS_ERR) //Obstacle
		{
			taskNo = 6;
		}

		if(SensorValue(lightLeft) >= MIN_SILVER_LEFT	 || SensorValue(lightRight) >= MIN_SILVER_RIGHT) //Rescue
		{
			taskNo = 7;
		}

		switch(taskNo) //Task Switcher
		{
		case 1:
			LineFollow();
			break;

		case 2:
			RegainLine();
			break;

		case 3:
			InclinationLineFollow();
			break;

		case 4:
			RightAngleTurns();
			break;

		case 5:
			IntersectionTurns();
			break;

		case 6:
			Obstacle();
			break;

		case 7:
			Rescue();
			break;
		}
	}
}
